[[redirects]]
  from = "/about"
  to = "dbsnepal.com/about"
  status = 200
  force = true
 
[[redirects]]
  from = "/services"
  to = "dbsnepal.com/services"
  status = 200
  force = true
 

[[redirects]]
  from = "/blog"
  to = "dbsnepal.com/blog"
  status = 200
  force = true
 
[[redirects]]
  from = "/contact"
  to = "dbsnepal.com/contact"
  status = 200
  force = true
 